from lib import *

CATALOG = """
SELECT pc.Name AS Category, ps.Name AS Subcategory, p.ProductNumber, p.Name AS Product, ISNULL(p.Color, '—') AS Color,
       p.StandardCost AS Cost, p.ListPrice AS Price,
       CASE WHEN p.ListPrice > 0 THEN (p.ListPrice - p.StandardCost) * 100.0 / p.ListPrice ELSE 0 END AS Margin,
       ISNULL(i.Qty, 0) AS Stock,
       CASE WHEN ISNULL(i.Qty, 0) < p.SafetyStockLevel THEN 1 ELSE 0 END AS LowStock,
       CASE WHEN p.SellEndDate IS NOT NULL THEN 1 ELSE 0 END AS Discontinued
FROM Production.Product p
JOIN Production.ProductSubcategory ps ON ps.ProductSubcategoryID = p.ProductSubcategoryID
JOIN Production.ProductCategory pc ON pc.ProductCategoryID = ps.ProductCategoryID
LEFT JOIN (SELECT ProductID, SUM(Quantity) AS Qty FROM Production.ProductInventory GROUP BY ProductID) i ON i.ProductID = p.ProductID
WHERE p.ListPrice >= @minPrice AND (@category IS NULL OR @category = '' OR pc.Name = @category)
ORDER BY pc.Name, ps.Name, p.Name"""

MUTED = "#6b7280"
# columns: number | product | color | cost | price | margin | stock
X = {"num": 8, "name": 100, "color": 360, "cost": 434, "price": 508, "margin": 582, "stock": 646}
W = 722  # usable width of A4 portrait with 36px margins


def build():
    detail = band("detail", 17, [
        field(X["num"], 1, 88, 15, "{p.ProductNumber}", size=8, color=MUTED),
        field(X["name"], 1, 255, 15, "{p.Product}", size=8.5),
        field(X["color"], 1, 70, 15, "{p.Color}", size=8, color=MUTED),
        field(X["cost"], 1, 62, 15, "{p.Cost}", "n2", size=8.5, align="right"),
        field(X["price"], 1, 62, 15, "{p.Price}", "n2", size=8.5, align="right", bold=True),
        field(X["margin"], 1, 56, 15, "{p.Margin}", "n1", size=8.5, align="right",
              rules=[rule("Margin", "lt", 30, color="#c2410c", bold=True), rule("Margin", "ge", 45, color="#15803d", bold=True)]),
        field(X["stock"], 1, 64, 15, "{p.Stock}", "n0", size=8.5, align="right",
              rules=[rule("LowStock", "eq", 1, bg="#fee2e2", color="#b91c1c", bold=True)]),
    ], source="p", rules=[rule("Discontinued", "eq", 1, color="#9ca3af")])

    bands = [
        band("reportHeader", 62, [
            rect(0, 0, W, 54, fill="#1e293b"),
            label(14, 8, 600, 22, "Product Catalog", size=17, bold=True, color="#ffffff"),
            field(14, 33, 690, 14, "List price ≥ {param:minPrice} USD  ·  category: {param:category}  ·  grey = discontinued, red stock = under safety level", size=8.5, color="#cbd5e1"),
        ]),
        band("pageHeader", 22, [
            label(X["num"], 4, 88, 14, "NUMBER", size=7.5, bold=True, color=MUTED),
            label(X["name"], 4, 250, 14, "PRODUCT", size=7.5, bold=True, color=MUTED),
            label(X["color"], 4, 70, 14, "COLOR", size=7.5, bold=True, color=MUTED),
            label(X["cost"], 4, 62, 14, "COST", size=7.5, bold=True, color=MUTED, align="right"),
            label(X["price"], 4, 62, 14, "PRICE", size=7.5, bold=True, color=MUTED, align="right"),
            label(X["margin"], 4, 56, 14, "MARGIN", size=7.5, bold=True, color=MUTED, align="right"),
            label(X["stock"], 4, 64, 14, "STOCK", size=7.5, bold=True, color=MUTED, align="right"),
            line(0, 20, W, "#9ca3af"),
        ]),
        band("groupHeader", 26, [
            rect(0, 2, W, 22, fill="#e0e7ff"),
            field(8, 6, 400, 16, "{p.Category}", size=11, bold=True, color="#312e81"),
        ], group=("p", "{p.Category}"), level=0, repeat=True),
        band("groupHeader", 20, [
            field(8, 3, 400, 14, "{p.Subcategory}", size=9, bold=True, color="#4338ca"),
            line(8, 18, 706, "#c7d2fe"),
        ], group=("p", "{p.Subcategory}"), level=1),
        detail,
        band("groupFooter", 20, [
            label(100, 3, 150, 14, "Products in subcategory:", size=8, italic=True, color=MUTED),
            field(254, 3, 40, 14, "{p.Product}", "n0", agg="count", scope="group", size=8.5, bold=True),
            label(330, 3, 170, 14, "avg list price", size=8, italic=True, color=MUTED, align="right"),
            field(X["price"], 3, 62, 14, "{p.Price}", "n2", agg="average", scope="group", size=8.5, bold=True, align="right", color="#4338ca"),
        ], group=("p", "{p.Subcategory}"), level=1),
        band("groupFooter", 8, [], group=("p", "{p.Category}"), level=0),
        band("pageFooter", 24, [
            line(0, 2, W, "#d1d5db"),
            field(0, 6, 300, 14, "Page {pageNumber()} of {totalPages()}", size=8, color=MUTED),
            label(300, 6, 422, 14, "AdventureWorks Cycles · generated by JetReportDesigner", size=8, color=MUTED, align="right"),
        ]),
        band("reportFooter", 30, [
            line(0, 4, W, "#1e293b", 1.5),
            label(8, 10, 160, 16, "TOTAL PRODUCTS", size=9, bold=True),
            field(180, 10, 60, 16, "{p.Product}", "n0", agg="count", scope="report", size=10, bold=True),
            label(300, 10, 200, 16, "AVERAGE LIST PRICE", size=9, bold=True, align="right"),
            field(X["price"], 10, 62, 16, "{p.Price}", "n2", agg="average", scope="report", size=10, bold=True, align="right"),
        ]),
    ]
    return report(
        "AdventureWorks — Product Catalog", "aw-product-catalog", "banded", bands=bands,
        sources=[sql("p", CATALOG, {"minPrice": "{param:minPrice}", "category": "{param:category}"})],
        params=[param("minPrice", "number", "Minimum list price", 0),
                param("category", "string", "Category (blank = all)", "", allowed=["", "Accessories", "Bikes", "Clothing", "Components"])],
        description="Two-level grouping, conditional formatting, aggregates per group and per report, repeating headers, page numbers.",
    )
