<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IisLogAnalyzer.Core\IisLogAnalyzer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>