<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PdfSharp" />
    <PackageReference Include="PDFsharp-MigraDoc" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="ZXing.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JetReportDesigner.Core\JetReportDesigner.Core.csproj" />
    <ProjectReference Include="..\JetReportDesigner.DataSources\JetReportDesigner.DataSources.csproj" />
  </ItemGroup>

</Project>
