<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JetReportDesigner.Storage.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JetReportDesigner.Core\JetReportDesigner.Core.csproj" />
  </ItemGroup>

</Project>
